apiVersion:apps/v1
kind:Deployment
metadata:
 name: nginx-deployment
spec:
 selector:
   matchLables:
     app: nginx
 replicas:2
 template:
   metadata:
     lables:
        app: nginx
   spec:
     containers:
      - name: nginx
        image: nginx:leatest
        ports:
        - continerPort: 80
       